### ISSUE TITLE
No proper error dialog when joining a room doesn't work

### ISSUE THREAD

**Issue by spoenemann** [TypeFox/open-collaboration-tools#30]
When I try to join a room with an invalid ID, I see the following in the server log:
```
Room with requested id r29cUYh_gFR0SoZ3F-6p4ci4 does not exist
Error occurred while joining a room Error: Room with requested id r29cUYh_gFR0SoZ3F-6p4ci4 does not exist
    at ConsoleLogger.createErrorAndLog (/workspace/open-collaboration-tools/packages/open-collaboration-server/lib/utils/logging.js:43:16)
    at /workspace/open-collaboration-tools/packages/open-collaboration-server/lib/collaboration-server.js:240:39
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
But nothing happens in VS Code. I'd expect an error dialog saying something like the room does not exist or is no longer open.

**Comment by msujew** [comment]
Fixed with https://github.com/TypeFox/open-collaboration-tools/pull/28.
